### PR TITLE
deprecate unused config option `timestamp`

### LINKED ISSUE #1044: Bug: unused config fields (silently ignored config flags)
**Describe the bug**

The config fields `daemon_dir` and `args` (in src/config.rs) and `timestamp` (in the generated config struct) are unused. I discovered this by running a very recent build of clippy (`cargo +nightly clippy`) on the code base instead of clippy using the configured version (1.63).
The `daemon_dir` and `timestamp` command line arguments (or in the config file) are silently ignored.

**Electrs version**
current master, 603830f1b921928089c558d90519b7ca0c0d4658

**To Reproduce**
2 ways:
- look at the clippy output (make sure to have the nightly toolchain installed with rustup): `cargo +nightly clippy`
- pass ignored flags to electrs binary (with or without `--timestamp`, timestamps are logged)

**Expected behavior**
assuming no future plans with the `daemon_dir` flag, that can be removed
if you ask me `timestamp` can just be removed, and the current behavior of showing timestamps can be kept as is
what is the current use of `args`? if I try to pass unknown flags I get an error, so I assume it is always empty then

rest of the issue template is not applicable to this as it is a code issue

### PR DESCRIPTION
**Pull request by antonilol**
closes #1044 

Feel free to edit any of the messages by directly committing (but review is still fine)

Is `std::process::exit(1);` desirable? This forces users to remove the flag with a nice message, in future releases they will get an error from the arg parser. When not exiting people might (and will) miss it, how many people look at the logs when booting a program? (thinking about one-click install full node distros for example)

### CODE REVIEW

File: src/config.rs [hunk 1]
```diff
@@ -282,17 +280,44 @@ impl Config {
             ResolvAddr::resolve_or_exit,
         );
 
+        let changed_daemon_dir = config.daemon_dir != default_daemon_dir();
+
+        let mut default_cookie_path = config.daemon_dir;
```
Comment (Kixunil) [inline src/config.rs:285]: Oh, wait, if daemon dir affects cookie maybe we should keep using it?

File: src/config.rs [hunk 2]
```diff
@@ -282,17 +280,44 @@ impl Config {
...
+        if changed_daemon_dir {
+            eprintln!(
+                "Error: `daemon_dir` is not used anymore and deprecated, \
+                please remove this option."
+            );
+            if config.auth.is_none() && config.cookie_file.is_none() {
+                eprintln!(
+                    "Set the `cookie_file` option to \"{}\" because \
+                    `daemon_dir` will be removed in a future release.",
+                    default_cookie_path.display()
```
Comment (Kixunil) [inline src/config.rs:305]: Very nice messages!

File: src/config.rs [hunk 3]
```diff
@@ -282,17 +280,44 @@ impl Config {
...
+                );
+            }
+            std::process::exit(1);
```
Comment (Kixunil) [inline src/config.rs:308]: I was going to suggest warning instead but since the messages are extra nice exit is better to ensure people see the nice ones. Also might make sense to exit after both messages were printed.

File: src/config.rs (hunk 1 above)
Comment (antonilol) [reply src/config.rs:285]: it only affects the default cookie location, and that is only used when no cookie and no username and password are set

File: src/config.rs (hunk 3 above)
Comment (antonilol) [reply src/config.rs]: > I was going to suggest warning instead but since the messages are extra nice exit is better to ensure people see the nice ones.

thought that as well

> Also might make sense to exit after both messages were printed.

done

File: src/config.rs (hunk 2 above)
Comment (antonilol) [reply src/config.rs:307]: thank you :)

File: src/config.rs (hunk 1 above)
Comment (Kixunil) [reply src/config.rs:285]: Yes, it could be somewhat useful for people who don't care to figure out the exact location of the cookie. But I could be convinced this is a too weird feature to support.

Comment (romanz) [reply src/config.rs:285]: Let's keep `daemon_dir` for now, and only remove `timestamp` in the PR.

**Review by romanz — APPROVED** [review]
Thanks!

**Comment by romanz** [comment]
@antonilol please squash the commits and update PR's title.

**Comment by antonilol** [comment]
Done!

**Comment by romanz** [comment]
Thanks!
